### ISSUE TITLE
Reservation de la table ne fonctionne pas!

### ISSUE THREAD

**Issue by b3rking** [Ngrano21/BarManager#2]
la reservation de la table ne fonctionne pas 
mais je crois que ca viens de la manque du chemin pour creer les fichiers temporaires
![Capture d’écran (4)](https://user-images.githubusercontent.com/31207091/123767326-a992e500-d8c7-11eb-86f9-27dad39c6ed1.png)

**Comment by Ngrano21** [comment]
La réservation marche il faut juste s'assurré 
que tu as un Dossier "temp" dans le dossier "src".
 Sinon on peut aussi rajouter une methode qui crée le dossier si ce dernier n'existe pas .
![Capture](https://user-images.githubusercontent.com/69772755/123871293-d7157800-d933-11eb-82f4-045c6d0e8bf5.PNG)
